dist: xenial
language: php

env:
  global:
    - SETUP=stable

matrix:
  fast_finish: true
  include:
    - php: 7.1.3
    - php: 7.2
      env: SETUP=stable

cache:
  directories:
    - $HOME/.composer/cache

services:
  - mysql

before_install:
  - phpenv config-rm xdebug.ini || true
  - mysql -e 'CREATE DATABASE forge;'
  - php artisan key:generate
  - php artisan storage:link
  - php artisan migrate
  - php artisan db:seed

install:
  - if [[ $SETUP = 'stable' ]]; then travis_retry composer update; fi

script: vendor/bin/phpunit