dist: xenial
language: php

env:
  global:
    - SETUP=stable

matrix:
  fast_finish: true
  include:
    - php: 7.1.3
    - php: 7.2
      env: SETUP=stable

cache:
  directories:
    - $HOME/.composer/cache

services:
  - mysql

before_install:
  - phpenv config-rm xdebug.ini || true
  - mysql -e 'CREATE DATABASE forge;'

install:
  - if [[ $SETUP = 'stable' ]]; then travis_retry composer update; fi
  - if [[ $SETUP = 'stable' ]]; then php artisan key:generate; fi
  - if [[ $SETUP = 'stable' ]]; then php artisan storage:link; fi
  - if [[ $SETUP = 'stable' ]]; then php artisan migrate; fi
  - if [[ $SETUP = 'stable' ]]; then php artisan db:seed; fi

script: vendor/bin/phpunit